_BASE_: "Base-ISTR.yaml"
MODEL:
  WEIGHTS: "./output-ISTR-AE-R50/model_final_istr_ae_r50.pth"
  RESNETS:
    DEPTH: 50
    STRIDE_IN_1X1: False
  ISTR:
    NUM_PROPOSALS: 300
    NUM_CLASSES: 8
    MASK_ENCODING_METHOD: "AE"
    PATH_COMPONENTS: "./projects/AE/checkpoints/AE_112_256.t7"
DATASETS:
  TRAIN: ("cityscapes_fine_instance_seg_train",)
  TEST:  ("cityscapes_fine_instance_seg_val",) #("cityscapes_fine_instance_seg_test",)
SOLVER:
  BASE_LR: 0.000015
  IMS_PER_BATCH: 4
  MAX_ITER: 48000
  STEPS: (18000, 36000) # 41.52
INPUT:
  MAX_SIZE_TEST: 2048
  MIN_SIZE_TEST: 1024
  MAX_SIZE_TRAIN: 2048
  MIN_SIZE_TRAIN: (800, 832, 864, 896, 928, 960, 992, 1024)
  CROP:
    ENABLED: False
  FORMAT: "RGB"
TEST:
  EVAL_PERIOD: 16000
