_BASE_: "Base-ISTR.yaml"
MODEL:
  BACKBONE:
    NAME: "build_swint_fpn_backbone"
  SWINT:
    EMBED_DIM: 192
    DEPTHS: [2, 2, 18, 2]
    NUM_HEADS: [6, 12, 24, 48]
    WINDOW_SIZE: 12
    MLP_RATIO: 4
    DROP_PATH_RATE: 0.3
    APE: False
    OUT_FEATURES: ["stage2", "stage3", "stage4", "stage5"]
  FPN:
    IN_FEATURES: ["stage2", "stage3", "stage4", "stage5"]
  WEIGHTS: "./swin_large_patch4_window12_384_22k_d2.pth"
  ISTR:
    NUM_PROPOSALS: 300
    NUM_CLASSES: 80
    MASK_ENCODING_METHOD: "AE"
    PATH_COMPONENTS: "./projects/AE/checkpoints/AE_112_256.t7"
LSJ_AUG: True
DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST:  ("coco_2017_val",) # "coco_2017_test-dev"
SOLVER:
  STEPS: (327778, 355092)
  MAX_ITER: 368750
  BACKBONE_MULTIPLIER: 0.1
  AMP:
    ENABLED: True