_BASE_: "Base-ISTR.yaml"
MODEL:
  WEIGHTS: "./torchvision-R-101.pkl"
  RESNETS:
    DEPTH: 101
    STRIDE_IN_1X1: False
  ISTR:
    NUM_PROPOSALS: 300
    NUM_CLASSES: 80
    MASK_ENCODING_METHOD: "PCA"
    PATH_COMPONENTS: "./projects/LME/coco_2017_train_class_agnosticTrue_whitenTrue_sigmoidTrue_256_siz112.npz"
DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST:  ("coco_2017_val","coco_2017_test-dev")
SOLVER:
  STEPS: (210000, 250000)
  MAX_ITER: 270000
INPUT:
  FORMAT: "RGB"
